version: "3.9"

services:
  web:
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./app:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:fpm-alpine3.15
    volumes:
      - ./app:/app